version: 0.2

phases:
  build:
    commands:
      - export ECS_CLUSTER_NAME=youth-llm
      - export ECS_SERVICE_NAME=youth-llm-task1-service-1
      - python Web/config/update_route53_ip.py

artifacts:
  files:
      - '**/*' # Include all source files in the artifacts
      #- imagedefinitions.json # Uncomment if you want to include this file