from django.db import models

# Create your models here.
class YouthPolicy(models.Model):
    policy_id = models.CharField(max_length=30, unique=True)
    delivery_method = models.CharField(max_length=50)
    name = models.CharField(max_length=255)
    keywords = models.CharField(max_length=255)
    description = models.TextField()
    main_category = models.CharField(max_length=100)
    sub_category = models.CharField(max_length=100)
    support_content = models.TextField()
    agency = models.CharField(max_length=100, blank=True, null=True)
    operating_agency = models.CharField(max_length=100, blank=True, null=True)
    application_period_type = models.CharField(max_length=50, blank=True, null=True)
    business_period_type = models.CharField(max_length=50, blank=True, null=True)
    business_start_date = models.CharField(max_length=20, blank=True, null=True)
    business_end_date = models.CharField(max_length=20, blank=True, null=True)
    etc_business_period = models.TextField(blank=True, null=True)
    application_method = models.TextField(blank=True, null=True)
    review_method = models.TextField(blank=True, null=True)
    application_url = models.TextField(blank=True, null=True)
    required_documents = models.TextField(blank=True, null=True)
    etc = models.TextField(blank=True, null=True)
    reference_url1 = models.TextField(blank=True, null=True)
    reference_url2 = models.TextField(blank=True, null=True)
    first_come_first_served = models.CharField(max_length=10, blank=True, null=True)
    min_age = models.CharField(max_length=10, blank=True, null=True)
    max_age = models.CharField(max_length=10, blank=True, null=True)
    marital_status = models.CharField(max_length=50, blank=True, null=True)
    income_condition = models.CharField(max_length=50, blank=True, null=True)
    etc_income_condition = models.TextField(blank=True, null=True)
    additional_qualification = models.TextField(blank=True, null=True)
    proposal_target = models.TextField(blank=True, null=True)
    view_count = models.IntegerField(blank=True, null=True)
    region = models.CharField(max_length=100, blank=True, null=True)
    major_condition = models.CharField(max_length=100, blank=True, null=True)
    employment_condition = models.CharField(max_length=100, blank=True, null=True)
    education_condition = models.CharField(max_length=100, blank=True, null=True)
    application_start_date = models.CharField(max_length=20, blank=True, null=True)
    application_end_date = models.CharField(max_length=20, blank=True, null=True)
    specialized_condition = models.CharField(max_length=100, blank=True, null=True)